"""change calculation

Revision ID: 50757ffb4f84
Revises: eedf493fc38c
Create Date: 2024-06-10 13:03:31.211217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50757ffb4f84'
down_revision: Union[str, None] = 'eedf493fc38c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_calculations', sa.Column('children_under_5_yo', sa.VARCHAR(length=32), nullable=True))
    op.add_column('saving_calculations', sa.Column('children_after_5_yo', sa.VARCHAR(length=32), nullable=True))
    op.drop_column('saving_calculations', 'children')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_calculations', sa.Column('children', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('saving_calculations', 'children_after_5_yo')
    op.drop_column('saving_calculations', 'children_under_5_yo')
    # ### end Alembic commands ###
