"""change table managesr add count_answers

Revision ID: e72f9ee858ae
Revises: 2d6e308e9d29
Create Date: 2024-04-17 04:02:17.626312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72f9ee858ae'
down_revision: Union[str, None] = '2d6e308e9d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managers', sa.Column('count_answers', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managers', 'count_answers')
    # ### end Alembic commands ###
