"""create db

Revision ID: eb8357732e55
Revises: 
Create Date: 2024-04-15 20:21:17.940189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb8357732e55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('forWhom', sa.String(), nullable=True),
    sa.Column('countMessage', sa.Integer(), nullable=True),
    sa.Column('message', sa.VARCHAR(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.SMALLINT(), nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('tg_first_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('tg_last_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('tg_username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=64), nullable=True),
    sa.Column('comment', sa.VARCHAR(length=64), nullable=True),
    sa.Column('is_block', sa.BOOLEAN(), nullable=False),
    sa.Column('discounts', sa.BOOLEAN(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False),
    sa.Column('first_gift_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_webinar', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('telegram_id > 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('webinars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('msg', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minicourses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('day_one', sa.Boolean(), nullable=True),
    sa.Column('day_two', sa.Boolean(), nullable=True),
    sa.Column('day_three', sa.Boolean(), nullable=True),
    sa.Column('day_four', sa.Boolean(), nullable=True),
    sa.Column('day_five', sa.Boolean(), nullable=True),
    sa.Column('day_six', sa.Boolean(), nullable=True),
    sa.Column('day_seven', sa.Boolean(), nullable=True),
    sa.Column('day_eight', sa.Boolean(), nullable=True),
    sa.Column('finish', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saving_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('men', sa.VARCHAR(length=32), nullable=True),
    sa.Column('women', sa.VARCHAR(length=32), nullable=True),
    sa.Column('children', sa.VARCHAR(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saving_calculations')
    op.drop_table('minicourses')
    op.drop_table('managers')
    op.drop_table('dialogs')
    op.drop_table('webinars')
    op.drop_table('users')
    op.drop_table('telegram_message')
    # ### end Alembic commands ###
