"""change table managesr add count_answers 2

Revision ID: eca8e0ef0a53
Revises: e72f9ee858ae
Create Date: 2024-04-17 04:26:56.573517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca8e0ef0a53'
down_revision: Union[str, None] = 'e72f9ee858ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('managers', 'count_answers',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('managers', 'count_answers',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
